name: care_connect_app

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2

  intl: ^0.18.1
  image_picker: ^0.8.6
  pdf: ^3.8.1
  printing: ^5.9.3
  timeline_tile: ^2.0.0
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.0
  provider: ^6.0.5
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  fl_chart: ^1.0.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/patient.jpg
    - assets/images/critical.jpg
    - assets/images/appointments.jpg
    - assets/images/reports.jpg
    - assets/ml-health-ajf9-edd3419d73b6.json
